version: '3.8'
services:
  naologic:
    build: .
    container_name: 'naologic'
    restart: always
    environment:
      PORT: 3000
      OPENAI_API_KEY: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..11n2KRPdxOJei4yB.8MkBoKNRGK-oZHeftBFFF-RwHi5c5j06xaXXpXKo9Ycon9KpAwvTG78eOcAQ8LbWl0VvjVzHt87_BdSkUSbc9xVr40DYW6nY7S56cIv9PkfWKJMqWzMvpS2tGHGMZ2e_9_-n2fAjWqEWh-DApTz7xCmbiEOBE-5LAl6anpn04DQYn7asTU6kqsTQEECbcX5BBu-0waB84Knbmd2o2gLxsqQwcb7VpUOX442cu8N8iL2zFEqShLoL5jfV5xvA_LytXbvxCx_dnahnE-RcKIpDnH_GnPrjH2UGEuqPSHoFAu9fBBAlAjLTawexsGlMly7sy3kvSFUemdWSUs0FDY5gFdZZjll1LeGxdpru4z8GEwMv5UPWw4cOCSKFsfqgujmqum2TTpeqP-Q8lyDl4iGOHIqP6wAbC4A_kMX6kRl_8EHTtzfXLeYi9wz7tiNKpPZG19iw1DdY9mthUrRW73FY5mjBA1VLnPSVybGp-JWgmnSFf1x_y4vcaizS21NIcae_mz4tVi0Q9ySK6Yq2jX-ACUmxlekcrxVBO7Wiboj5Lcjkl2WsTFNiHrjc34evwfOswozOFwMIgbbvs80B6olegblEvUFnyLS0Jr57Dhdevd8YK9QuUNn2BQSVb8Lsg7cLKyv29aWpLekZ2BUh5O92oEMo-Mu0_ZpqgsoTdRD6vVir0qJC66NT47LXe0C32LJ5ekR09cHe4zqvew7u1WAR46wygZaF9nty5D--N-0XF9nJbfUojAuT9B3Bubj0yaXpWOz2Q3k3tEMQKk6Mq_QRiL1ulzLKE9qHzGptWu-JkgwAOAdM2lTWOSVZ9hiJWYmvunRBiiGXbAeVvho5Yf64B2XnQRjuoMYu3kenc3MA39lUFtvL01FKbWJXFXzX0uPNB9VQRQBDO46yEptIxkeEEITjGElPJPP1lYYr8g4qad2spfEO1v-9RJlDnulIWRD34DT6u-iHhxkJNWzZrJMy5pQ9TBPJotUR_HOS8cC_V55ROFZLdIrgPlNrRRH_jyTHW-2IRy5Sw4H087mozM4v0FdOkaMedWvMRWgssCqceGteuFYc9KeYW9BxwdJ3npsXhfmg3Pe2NxwfaLqEeKrgiEyc0jaCpQ4eZorFrGjDJXJ3GWi43u5Uq09TCSV8Wts6wyqtI7ai5VDWZJmxIs4b5tx7aTaeAWWPaK2jwW_3rHCU1JzMAfLsm_LUwF8Mq46-qHXrHTeOrv2XhTdiKhGE9B8YBXtY46TY5Ijfe5cAZ7xhsh2YuoXnu7nFhw_fQZlhadvH1cG3elxFsYA9bhCLUDUc2GOtTBUrPICMwefpj6qX905dBpdp0kN2lHxbiZH8-LaQtTso5vpQw1XcK1_GrK6-ZGBlJUbhvcP7uB9XkgUkTcVLKMrataiO5dazpDe5KqX6jbDbc59aiW2vuOpPL5WZWlTDRlwh1KLmznDuvdxEFu5vFDhBiR2cGb3OAeip_eQTWPmCvHLGunAdWaUJsvt8EaC-aQyBjLMAq0f4EbeK4nYbnHPzRJskHJsGXIFPh6oRTKC1vHIgcmKKQPM01EynpRlBLKo0VbIAYqd2MJEdMS3qqCVGHsio63Gofooefr7udyjZcTNwJS3XYtPQLnkbSfHOBIO0YFkjwMxIdyiJpki-3S9-gdL6euHNNA9AVasddVrmeIDzt5k-jprTyEatwwwZyDyNG7wsD3tEJoQ61Ks5_IrnNp9X3MJQBnx1dIFwkGvlM7JSa7j2o1s7dw5nrqm-h8Dui0V6V_betJSCU_oVAL0TnT0H0O1gkhTjrZqusYEVYuiwF5bjK12Ces5ba2YjA2PFP563ekiqwBVES5ebonnMNbBocy2wSRzzYQ2ETFwiTWSZO9L38iGUwch02sOvholBbvuYdHPbTkLTppyoBqr9B-xq2ZS8ZGHiiDVgGcLcvNuXt70JzYsF8eoPPS9SMQX-pNFoS13SJnrMJKYQyns_4lblJ0IBpfMCA_osPsMXSdkfzpi7QaeAOHlHTAIB7qRv5I3WtPjH2yQb1nxIeDfCLNuE3lVayiQMgiq6ZSccp9cAwNDaqZRZclgEIkSsBF5KBmj_LvlPmFpF2Vh0me5_bdcfPilJ0a2IJg6lGSj34NDaJY8DHDgyhFWJa_NRj8ppEF4gM1sropshdB23gxRviGkVFgI4gwcugqMVWrvaf34IfspMmPZJBKOlUDKAfywhdpmI5Q4VyrrOaRUTI_zMqqeZ6joz1NfP3I4AXyH3wA7Wucflkz1T-B1RvyWHkRre66Ld_pZCnR3T-F3auRU7TPgl_NXpdnqLe9lt7KlQbcFb2Gp84r9tzqOqsr4hiv_CNcv49OZo-Zkt7MImfMCsvhFJjV2Yy0T71Sh9S_VrThbnzZFHxbyYPjI0QFuA6fd8nKVAQH7DRT--dDLOYow2e0F7480NLmPG2cScQUpNFJQa3S41B-D3-dRTDX7cwNLz9gQ57dJo5aLtMyofwt0eV7D9Ocv7N8P4VVzqeCFdqLEBbFseMqHDd79CUOhi8acyU1d8HUfyLaap0A71vgjQuGc6cE3X2TecyZ2SglI2YTH2hYoJIkagACrhSTV6PgnjO0fMOLBFxlSTIbZhsNWhwjy_iZId6_hrMc69Yb1JYe9sqh13chqIPKQ09p1iml9L8HHH5HYCkSkcP3Cp8c8vLvczMqldWUO_d9EWv68CLUiBaZZLt6aYXRWvgPuqRjZ0u79_bYNpH-lkMUrByF8hPapiqSgzPjuBsH3ApDqnxUR-ebyyPE-zRXaHnw24H2mCwiV_5HKfgjdhXc7g21ipgpUnBNPpRiqcreXTVI6rLoyqQ2BzsXhDl0whTjzlVKgAyY7AjBXnFhgW9hqemDvKyA8Yqa6fL8Vp3V9yXAi7gQh9x0akqoH6N5oy5DD7SFgs6fSX85icqURPpLAIkdQghVE_fKO7RpcHEceWW2LW9RWlFJlE_F7pnhd17kFjsRlKlMcFN6J4pkEdEVekhcPZAkT2R74NVKCM-E5oaNACQ2vKLAVcyIvp3T00Uwmu2giJlyIRJAy9OJBXyA.P7P8V7OeuwtsX4meeuxMvg
      ORGANIZATION: org-qUSn0nRCpnrCsavk4yGfqX49
      NODE_ENV: 'local'
      MONGODB_URI: 'mongodb://mongodb:27017/naologic'
    deploy:
      resources:
        limits:
          memory: 2G

    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - naologic-network

  mongodb:
    image: mongo
    ports:
      - '27019:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - naologic-network

volumes:
  dbdata:

networks:
  naologic-network:
    driver: bridge